#!/usr/bin/env bash

#
# This scripts configures the compiling files of PHP-7.4.9
#
# To test, run "make test"
#

. common.sh

SRC_DIR="$PROGRAMS/php-7.4.9"

export CC="$CC"
export CXX="$CXX"
export CFLAGS="-flto"
export CXXFLAGS="-flto"
export LD="$CC"
export LDFLAGS="-fuse-ld=lld $DYN_STATS_PASS -lstdc++ $ANALYSIS_LIB/libanalysis.o"
export AR="$AR"
export NM="$NM"

cd $SRC_DIR
#
# Clean files from old builds
#
if [[ -f "Makefile" ]]; then
    make -k clean
fi

#
# Configure
#
if [[ -f configure ]]; then
    ./buildconf --force
fi
./configure --prefix="$SRC_DIR/build"                   \
            CC="$CC"                                    \
            CXX="$CXX"                                  \
            LD="$CC"                                    \
            CFLAGS="$CFLAGS"                            \
            CXXFLAGS="$CXXFLAGS"                        \
            LDFLAGS="$LDFLAGS"

#
# For some unkown reason, $LDFLAGS is not written to the generated Makefile
# (but -flto is there for $CFLAGS. Here we manually set the LDFALGS in the
# Makefile. Also, for another unknown reason, the $LDFLAGS cannot have
# "-fuse-ld=lld"; it would otherwise reports a "invalid linker name in argument '-fuse-ld=lld -Wl,-mllvm,-get-obj-size'"
# error during linking.
#
sed -i "1iLDFLAGS=$LDFLAGS" Makefile

# Remove existing data file.
clean_stat_files

#
# Compile
#
if [[ $1 == "make" ]]; then
    make -j8
    make install -j8
fi

#
# Remove dyanmic data files generated by the compiling.
#
rm -f /tmp/analysis_result.stat
