#!/usr/bin/env bash

#
# This scripts builds redis-6.2.5.
#
# To test, run "make test"
#

. common.sh

SRC_DIR="$PROGRAMS/redis-6.2.5"
BUILD_DIR="$SRC_DIR/build"

CC="$CC"
CXX="$CXX"
CFLAGS="-flto"
CXXFLAGS="-flto"
LD="$CC"
LDFLAGS="-fuse-ld=lld"
LDFLAGS="$LDFLAGS -lstdc++ $DYN_STATS_PASS $ANALYSIS_LIB/libanalysis.o"
# LDFLAGS="$LDFLAGS $GET_OBJ_SIZE_PASS"
AR="$AR"
NM="$NM"

#
# Clean old stats
#
clean_stat_files

cd $SRC_DIR
if [[ -f "Makefile" ]]; then
    make -k clean
fi

#
# Compile and install
#
make CC="$CC" CFLAGS="$CFLAGS" LDFLAGS="$LDFLAGS" -j8
make PREFIX="$BUILD_DIR" install

# Remove the dynamic stat file generated by compiling.
rm -f /tmp/analysis_result.txt
