#!/usr/bin/env bash

#
# This scripts builds sqlite-3.37.0
#
# To test, run "make test".
#
# Official Doc: https://sqlite.org/src/doc/trunk/README.md
#

. common.sh

SRC_DIR="$PROGRAMS/sqlite-3.37.0"
BUILD_DIR="$SRC_DIR/build"

#
# The "Var=Val" setting following configure does not work. We need export.
#
export CC="$CC"
export CFLAGS="-flto"
LDFLAGS="-fuse-ld=lld"
export LDFLAGS="$LDFLAGS $DYN_STATS_PASS -lstdc++ $ANALYSIS_LIB/libanalysis.o"
# export LDFLAGS="$LDFLAGS $GET_OBJ_SIZE_PASS"
export AR="$AR"
export NM="$NM"
export RANLIB="$RANLIB"

#
# Start to build
#
mkdir -p $BUILD_DIR
cd $BUILD_DIR
if [[ -f "Makefile" ]]; then
    make clean
fi

#
# Configure
#
../configure
#
# Remove existing data file.
#
clean_stat_files

#
# Compile
#
if [[ $1 == "make" ]]; then
    make -j8
fi

# Remove the dynamic stat file generated by compiling.
rm -f /tmp/analysis_result.txt
