# This Makefile is an debugging helper.

OLDEN = ./olden.sh

bh:
	$(OLDEN) bh

bisort:
	$(OLDEN) bisort

em3d:
	$(OLDEN) em3d

health:
	$(OLDEN) health

power:
	$(OLDEN) power

tsp:
	$(OLDEN) tsp

clean:
	./olden.sh clean
